# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-08 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='likes',
            field=models.ManyToManyField(related_name='user_likes', to='socialapp.Post'),
        ),
    ]
