# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-07 20:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0002_userprofile_friends'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-post_time']},
        ),
        migrations.AddField(
            model_name='post',
            name='post_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 3, 7, 20, 5, 31, 938932, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
