# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-08 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0004_auto_20160308_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_tags',
            field=models.ManyToManyField(to='socialapp.Tag'),
        ),
    ]
